### ISSUE TITLE
Perfect!!

### ISSUE THREAD

**Issue by vegasbrianc** [mikesir87/cats#1]
Thanks for making this repo. This is exactly what I was looking for to present Swarm that is not the standard ping script. Great work!

**Comment by mikesir87** [comment]
Haha... glad you like it!  But, I need to update the README and give proper credit, as it's actually a semi-fork of the [DockerCon orchestration lab](https://github.com/docker/dcus-hol-2016/tree/master/docker-orchestration).  So... can't take full credit for it.  

But, funny how it's the Docker image that's gotten far more pulls than all of my other ones combined ;)
